### ISSUE TITLE
levante-emv.com

### ISSUE THREAD

**Issue by mapx-** [easylist/easylistspanish#1]
https://github.com/reek/anti-adblock-killer/issues/2766

**Comment by diaux** [comment]
Thanks for reporting this one. I checked the website, and I could only see the anti adb once, for a brief period of time, then it disappeared on its own. I have not been able to reproduce it again ever since, I tried multiple things without any luck. I have, however, added the following two filters into EasyList Spanish...

```
@@||levante-emv.com/*ads$script
@@||levante-emv.com^$generichide
```
...commit 43bc636. Thanks.

**Comment by diaux** [comment]
For the record: I was able to reproduce the anti adb message now. It appears only if you are using Chrome. I always check websites using Firefox, but it looks I looked at this website using Chrome, then switched to Firefox and continued there. That's why I wasn't able to reproduce it again.
